services:
  medical-ai:
    build: .
    container_name: medical_assistant
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./Historia_wizyt.db:/app/Historia_wizyt.db
    deploy:
      resources:
        limits:
          memory: 8gb 

  nginx:
    image: nginx:latest
    container_name: nginx_gate
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - medical-ai
    restart: always